[[plugins]]
repo = 'LuXuryPro/deoplete-rtags'
hook_add = '''
  let g:deoplete#sources.cpp = ['buffer', 'rtags']
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_start_level=1
  let g:indent_guides_guide_size=1
  let g:indent_guides_enable_on_vim_startup=1
  let g:indent_guides_color_change_percent=3
  if !has('gui_running')
    let g:indent_guides_auto_colors=0
    function! s:indent_set_console_colors()
      hi IndentGuidesOdd ctermbg=235
      hi IndentGuidesEven ctermbg=236
    endfunction
    autocmd VimEnter,Colorscheme * call s:indent_set_console_colors()
  endif
'''

[[plugins]]
repo = 'google/vim-colorscheme-primary'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme primary
'''

